/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package bancodados;

import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ControleAcesso extends javax.swing.JInternalFrame {
   String situacao;
    
    
    
    public ControleAcesso() {
        initComponents();
        this.jCodigo.setEnabled(false);
        AtualizarTable();
        try {
            setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ControleAcesso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void AtualizarTable(){
        try {
            Connection conexao = ConexaoMysql.conexaoBanco();
            String sql = "SELECT * FROM login ORDER BY id_login;";
            PreparedStatement stmt = conexao.prepareStatement(sql);
            DefaultTableModel tabela1 = (DefaultTableModel) tabela.getModel();
            tabela1.setNumRows(0);
            ResultSet rs = stmt.executeQuery();
            while(rs.next()){
                Object[] dados = {rs.getString("id_login"),rs.getString("usuario"),rs.getString("situacao"),rs.getString("tipo_usuario"),rs.getString("resetar_senha")};
                tabela1.addRow(dados);
            }
            stmt.close();
            rs.close();
            conexao.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(ControleAcesso.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSituacao = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jUsuario = new javax.swing.JTextField();
        jTipoUsuario = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btCadastrar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btResetarSenha = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rAtivo = new javax.swing.JRadioButton();
        rInativo = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Controle de Acesso");

        jLabel1.setText("Usuario");

        jLabel2.setText("Tipo de Usuário");

        jTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Tipo", "Admin", "Normal" }));

        tabela.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabela.setForeground(new java.awt.Color(102, 102, 102));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Usuário", "Situacao", "Tipo Usuário", "Resetar Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        btCadastrar.setText("Cadastrar");
        btCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCadastrarMouseClicked(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAlterarMouseClicked(evt);
            }
        });
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btResetarSenha.setText("Resetar Senha");
        btResetarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btResetarSenhaMouseClicked(evt);
            }
        });

        jLabel3.setText("Código");

        jLabel4.setText("Situação");

        grupoSituacao.add(rAtivo);
        rAtivo.setText("Ativo");
        rAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAtivoActionPerformed(evt);
            }
        });

        grupoSituacao.add(rInativo);
        rInativo.setText("Inativo");
        rInativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rInativoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCadastrar)
                        .addGap(61, 61, 61)
                        .addComponent(btAlterar)
                        .addGap(61, 61, 61)
                        .addComponent(btResetarSenha))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(63, 63, 63)
                        .addComponent(rAtivo)
                        .addGap(18, 18, 18)
                        .addComponent(rInativo)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rAtivo)
                    .addComponent(rInativo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btAlterar)
                    .addComponent(btResetarSenha))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastrarMouseClicked
        try {
            Connection coin =ConexaoMysql.conexaoBanco();
            String sql = "INSERT INTO login(usuario,senha,tipo_usuario)"
                    + "VALUES(?,UPPER(MD5('Mudar123')),?);";
            PreparedStatement stmt = coin.prepareStatement(sql);
            stmt.setString(1,this.jUsuario.getText());
            stmt.setString(2,this.jTipoUsuario.getSelectedItem().toString());
            stmt.execute();
            JOptionPane.showMessageDialog(null, "Usuario cadastrado com sucesso!!");
            AtualizarTable();
            
            
            this.jUsuario.setText(null);
            this.jTipoUsuario.setSelectedItem("Selecione o Tipo");
            
        } catch (SQLException ex) {
            Logger.getLogger(ControleAcesso.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_btCadastrarMouseClicked

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
      this.jCodigo.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
      this.jUsuario.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
      situacao=tabela.getValueAt(tabela.getSelectedRow(),2).toString();
      this.jTipoUsuario.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
      
      if(situacao.equals("A")){
          this.rAtivo.setSelected(true);  
      }else if(situacao.equals("I")){
          this.rInativo.setSelected(true);
      }
      
      
      
        
        
        
    }//GEN-LAST:event_tabelaMouseClicked

    private void btResetarSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btResetarSenhaMouseClicked
       try {
           Connection con = ConexaoMysql.conexaoBanco();
           String sql = "UPDATE login SET resetar_senha = 'S',senha=UPPER(MD5('Mudar123')) WHERE id_login=?;";
           PreparedStatement stmt = con.prepareStatement(sql);
           stmt.setString(1, this.jCodigo.getText());
           stmt.executeUpdate();
           stmt.close();
           con.close();
           JOptionPane.showMessageDialog(null,"Senha do "+this.jUsuario.getText()+" foi resetada para o padrão");
           AtualizarTable();
       } catch (SQLException ex) {
           Logger.getLogger(ControleAcesso.class.getName()).log(Level.SEVERE, null, ex);
       }
       
    }//GEN-LAST:event_btResetarSenhaMouseClicked

    private void rAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAtivoActionPerformed
        situacao = "A";
    }//GEN-LAST:event_rAtivoActionPerformed

    private void rInativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rInativoActionPerformed
        situacao="I";
    }//GEN-LAST:event_rInativoActionPerformed

    private void btAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMouseClicked
       try {
           Connection con = ConexaoMysql.conexaoBanco();
           String sql = "UPDATE login SET usuario =?,situacao=? WHERE id_login=?;";
           PreparedStatement stmt = con.prepareStatement(sql);
           stmt.setString(1, this.jUsuario.getText());
           stmt.setString(2, situacao);
           stmt.setString(3, this.jCodigo.getText());
           stmt.executeUpdate();
           
           stmt.close();
           con.close();
           this.AtualizarTable();
           JOptionPane.showMessageDialog(null, "Código "+this.jCodigo.getText()+" Modificado em Usuario ou situacao");
       } catch (SQLException ex) {
           Logger.getLogger(ControleAcesso.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        
        
        
    }//GEN-LAST:event_btAlterarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btResetarSenha;
    private javax.swing.ButtonGroup grupoSituacao;
    private javax.swing.JTextField jCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jTipoUsuario;
    private javax.swing.JTextField jUsuario;
    private javax.swing.JRadioButton rAtivo;
    private javax.swing.JRadioButton rInativo;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
